POST http://localhost:8080/events

content-type: application/json

{
    "name":"manchester festival",
    "description" : "festival",
    "location": "Manchester",
    "dateTime":"2025-01-01T15:30:00.000Z"
}